name: sickler
description: A Sickle Cell Help App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0+1
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.251
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  fpdart: ^1.1.0
  go_router: ^14.1.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.1.5
  flutter_riverpod: ^2.4.0
  cloud_firestore: ^5.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  mesh_gradient: ^1.3.7
  flutter_spinkit: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  icon_font_generator: ^4.0.0
  mocktail: ^1.0.3
  isar_generator: ^3.1.0+1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/fonts/
   - assets/images/
   - assets/svg/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
#    - family: My Icons
#      fonts:
#        - asset: assets/fonts/my_icons_font.otf